### ISSUE TITLE
First part of selenium tests for Bachelor

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/seleniumTests#1]
Assigned to @bduffany & @hciwork 

Click checkboxes after each test is done

LandingPage/Login
- [x] Login div appears
- [x] Login with invalid username
- [x] Login with invalid password
- [x] Login takes you to user's home (the one with the project-list and menu)

User's homepage
- [x] Upload project (single file)
- [x] Create new project with no project name
- [x] Create new project with valid project name
- [x] Create new project with invalid name (e.g. backslashes in project name)
- [x] Upload project (need to test zip functionality, is that possible?)

Sketch page
- [x] Boards dropdown (does it exist?)
- [x] Board selection from dropdown (must be on the placeholder after selection)
- [x] Ports dropdown (does it exist?)
- [x] Run On Arduino with empty ports dropdown (none selected)
- [x] Speeds dropdown (does it exist?)
- [x] Open Serial Monitor with empty ports dropdown
- [x] Clone project (does it take you to a "projectName copy" page?)

**Comment by bduffany** [comment]
I hit an unexpected roadblock where the Selenium webdriver for Firefox runs without extensions, so the ports dropdown, flash button, etc. aren't visible to the webdriver. I'm trying to see if anyone has run into this issue before and if there are any workarounds.

**Comment by tzikis** [comment]
Hey Brandon,
Yes, you are right. From the little research we've done in the past, it looks like there's no way to control that, which is a huge bummer, since we can't test things like the getting started walkthrough, etc. At the same time, we wouldn't be able to test a successful or unsuccessful Arduino flashing anyway, since you would need to mock an Arduino device for that.

My advise would be to see if anyone had found a workaround for this, but if no one hasn't, just move on to the rest of the tests.

Tzikis

**Comment by bduffany** [comment]
I'm assuming "Open Serial Monitor with empty speeds dropdown" should really say "Open Serial Monitor with empty ports dropdown," since it doesn't look like it's possible for the speeds dropdown to be empty.

**Comment by bduffany** [comment]
Also, I am slightly confused by a particular behavior with the sketch page. If the user clicks "USB Flash," it simply shows an error message. But if the user clicks "Open Serial Monitor," the port and speed dropdowns both become disabled. Why does the behavior differ for these two cases?

**Comment by fpapadopou** [comment]
Ok @bduffany I've updated the issue description (replaced speeds dropdown with ports dropdown)

**Comment by fpapadopou** [comment]
@bduffany it's obviously a bug, which we've fixed in a next version of the sketch page. The "disabling" of the port and speed dropdowns takes place because a user is not supposed to change either the speed or the selected port while having the serial monitor open. In your case, there should be a check whether the ports dropdown is empty or not. However, you can still check that the two dropdowns are disabled after clicking on "Open Serial Monitor"

**Comment by fpapadopou** [comment]
By the way @bduffany @hciwork what's the status with the `User's homepage`?

**Comment by bduffany** [comment]
I've already begun writing some tests for that, and will probably be able to finish those up this weekend before moving onto the next issue. I haven't actually committed those tests though, because for some reason I'm having trouble getting them to run automatically. I must have a minor issue somewhere that's preventing `py.test` from recognizing them.

**Comment by bduffany** [comment]
I did have one question about the `User's homepage` tests though -- what's the difference between the first and last checkbox?

**Comment by fpapadopou** [comment]
@bduffany the first box stands for single file upload, in other words, uploading a single .ino file (not empty). This will end up in a new project with the name of the .ino file.
The last checkbox stands for multi-file upload (zip files). Let's say you have created a folder and place your .ino file in it, as well as a header file that is used by the project. Then zip the folder and upload it to the bachelor. You should now have a new project named after the .ino file, containing two files (.ino and .h)
Sorry for not making it clear in the first place.

**Comment by fpapadopou** [comment]
All is done here, so I'm closing the issue
