### ISSUE TITLE
Second part of selenium tests for Bachelor

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/seleniumTests#2]
Assigned to @bduffany & @hciwork 

Some more test cases for the Bachelor.

Click checkboxes after each test is done

Sketch Page
- [x] Add new file to project with new filename
- [ ] Add new file to project via upload new file
- [ ] Add new file to project via upload new file with error (unsupported file)
- [x] Delete a file - check the modal that pops-up
- [x] Delete a file - refresh and verify that it's deleted
- [x] How about the progress bar? I guess this only applies to the verify action

Boards (supported boards) page
<b>Note:</b> You can use one of the board definitions found here https://github.com/arduino/Arduino/blob/ide-1.0.x/hardware/arduino/boards.txt
- [x] File successful upload
- [x] File upload with error
- [x] Delete board button
Ignore the `Edit board` button, it's not working on bachelor codebender version

**Comment by hciwork** [comment]
In order to test the upload interface for supported and unsupported file types, I think I need to pass the filepath using driver.execute_script(), but I'm not sure what script handles the upload form.

 Is there a better way of handling this?

**Comment by hciwork** [comment]
I'm not sure how to do a file upload when the input type for the form is "hidden."
I get an ElementNotVisible exception.

Also, even when I upload a .h file manually, it says that the file type is unsupported.

**Comment by tzikis** [comment]
Where are you trying to upload the .h file, in the homepage/dashboard, or inside the editor page after opening a project?

The first one won't work, since we can only create a project from a .ino file, or a .zip containing an .ino and any other .h/.cpp files. The second one will add the .h file to a preexisting project

**Comment by bduffany** [comment]
Have you tried testing uploads on the supported boards page? The file input isn't hidden (it's just offset beyond the left edge of the screen), so the approach described [here](http://stackoverflow.com/questions/9726005/how-to-click-on-input-type-file-across-browsers-using-selenium-webdriver) might work.

**Comment by hciwork** [comment]
i haven't tested the supported boards page.
i'll take a look.
it's strange that they're implemented differently.

**Comment by hciwork** [comment]
on the bachelor version, i tried to manually upload both .h and .c files using the upload/dropzone form after clicking on the "add new file" icon for test_project.ino.  it continues to give an error saying it's an invalid file type.

**Comment by fpapadopou** [comment]
@hciwork my guess is you're trying to upload an empty file. On Ubuntu, if you right-click and "create a new document" (pretty much like running `touch document_name.h` on the command line), the document has a size of zero bytes, which makes it fail to upload. If you write at least one character in the file, then its size becomes non-zero and you can upload it to the dropzone.
That should help you complete your tests.

**Comment by hciwork** [comment]
ok thanks! i'll take a look.
