### ISSUE TITLE
Independent tests for cb_compile_tester's projects

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/seleniumTests#3]
Assigned to @bduffany & @hciwork

For this one, you'll have to compile the projects of a user called cb_compile_tester (https://codebender.cc/user/cb_compile_tester). It's a fake user whose projects are weird cases we've come across during the past months.  We'd like to be able to test all of cb_compile_tester's projects at once and get a structured output containing which of them compiled successfully and which didn't.

<b>Update 1</b>
The /libraries testing task was removed and placed into a separate issue.

<b>Update 2</b>
Following the same pattern as on #6, we could add the ability to only run the tests for cb_compile_tester's projects, like `python run_tests.py --compile-tester` and we could also choose which codebender instance we'd like to test, so the above command would become `python run_tests.py --compile-tester --url http://localhost` in order to test cb_compile_tester's sketches your bachelor instance.
Remeber that on bachelor you will have to use `verify()` JavaScript function instead of `compilerflasher.verify()`.

<b>Update 3 (assuming we have accomplished testing `upload` functionality)</b>
Having added the ability to choose which codebender instance we want to test, we can stick to the bachelor (remember it's our open source version). You might have noticed that there is no cb_compile_tester on the bachelor version you have installed on your VMs :anguished:
What we thought you could do, is add all cb_compile_tester's to the tests repo in zip files, and then login with tester user, upload each one of the zip files, compile the project and report the result.
After the compilation of each sketch, you could have the tests delete it. This way we can test the whole "upload a project, use it and then delete it" process.

**Comment by bduffany** [comment]
Do we also want structured output for `/libraries`? Or would it make sense to have those tests simply fail as usual if one of the tests doesn't compile?

**Comment by fpapadopou** [comment]
@bduffany We'll have to get some structured output (most likely in JSON format) and store it somewhere locally. We can continue this discussion on the #6

**Comment by bduffany** [comment]
I figured out a [super hacky] way to upload things to the user's homepage:
1. Using JavaScript, create an artificial `<input type="file">` element (with `fixed` positioning, so it doesn't mess with anything), and insert it into the DOM
2. Using Selenium, populate that `input` with a local file
3. Using JavaScript again, get the `file` object now stored in this `input`, and manually fire the `drop` event of the `Dropzone`, passing in an object containing this `file`.

It's pretty dumb that I had to do this for a simple file upload... Selenium should really support drag and drop out of the box

**Comment by tzikis** [comment]
welcome to the real world, where everything is crappy and "sort of works",
as long as it's Wednesday :P

**Comment by hciwork** [comment]
nice creativity.
selenium actually does support drag and drop, although i'm not sure if it would work for your case.
http://selenium-python.readthedocs.org/en/latest/navigating.html#drag-and-drop

**Comment by bduffany** [comment]
Woops, accidentally clicked "close." Reopening.

**Comment by bduffany** [comment]
I'm not sure I see what *Update 3* is trying to achieve - several of `cb_compile_tester`'s projects currently do not compile, so I'd essentially be committing a bunch of broken code to the repo, and the tests would always fail. Wouldn't it make more sense to have the test automatically download all of `cb_compile_tester`'s libraries each time, and upload them to the bachelor version? But even then, do we  expect that some tests that don't compile on the live site will give different results for the Bachelor version?

**Comment by fpapadopou** [comment]
@bduffany the tests should succeed if the compilation request is completed successfully. The point of the test, is to get a report of which of the cb_compile_tester's projects compile and which don't.
If one of the compilation requests fails to complete, then the test should fail.
This means you will have to commit all of cb_compile_tester's projects either way. 
In the context of creating an *open source* project that tests another *open source* project, you'll have to manually upload the projects and not fetch them from an external source (such as the codebender live website).

**Comment by bduffany** [comment]
This makes sense, also @tzikis explained this to me during the Skype call on Friday. I've implemented those tests as part of #7.
