### ISSUE TITLE
Independent tests for codebender libraries

### ISSUE THREAD

**Issue by fpapadopou** [codebendercc/seleniumTests#6]
<b>Initial /libraries task</b>
For this one, we need you to iterate over all the examples found in https://codebender.cc/libraries page and check whether the code compiles or not. For example, under the Ethernet library, you have the UDPSendReceiveString example. So you open example (https://codebender.cc/example/Ethernet/UDPSendReceiveString), select Arduino UNO board (for now at least) and then compile the code. You might notice that the only option you have on a library example page, is to `Run on Arduino`, which means compile the code and then upload the code on the board. So if we just want the compilation part, we can call the corresponding Javascript. If you try calling `compilerflasher.verify()` then you will get the compilation result only without any attempt to load the code on the board. And this will output either a success message or an error message. 
So we kind of want to automate this for all the examples found on the /libraries page of the live codebender website.
After the test execution, we should be able to get the output with the successful and unsuccessful examples in JSON format.

<b>Update 1</b>
It would also be good to have the ability to run the tests only for the libraries,
for example (supposing that the command `python run_tests.py` runs your tests)
something like `python run_tests.py --libraries` could run the tests for the /libraries page.

<b>Update 2</b>
Expanding one library's examples and then selecting an example and compiling it is pretty much the same in the bachelor as well as the live website. So we thought we could also use your tests for the bachelor too (reminder: bachelor is open source and your tests are supposed to test an open source project). In this case we could have the tests get the url of the version of the site that we want to test, for example (assuming same things as Update 1) `python run_tests.py --libraries --url http://localhost` in order to test your bachelor's library examples.
Note that on the bachelor, you will have to use `verify()` JavaScript function instead of `compilerflasher.verify()` (maybe you could first check if `compilerflasher` is defined, and if not, then just use `verify()`)

**Comment by bduffany** [comment]
What you've described in Update 1 is already possible. Rather than running `tox`, just run `py.test tests/libraries`. This tells `py.test` to only collect tests from the `tests/libraries` directory, rather than the entire `tests` directory.

**Comment by bduffany** [comment]
However, this won't run the tests within `virtualenv`. There's probably a simple workaround for that.

**Comment by fpapadopou** [comment]
@bduffany perfect! Not sure about the `virtualenv` issue. I'll check it out.
