### ISSUE TITLE
Option to run minimal set of tests

### ISSUE THREAD

**Issue by bduffany** [codebendercc/seleniumTests#9]
We should have an option like `--minimal` (or its complement, `--full`) to run the absolute basic tests. Right now when we run `tox` it goes through and uploads all of `cb_compile_tester`'s projects, and also compiles every single one of the libraries. Instead we should have the option to only compile one from each category, just to verify basic functionality, and to make sure all tests pass.

**Comment by bduffany** [comment]
(This is a very simple feature to implement which shouldn't take me more than an hour or so to implement)

**Comment by fpapadopou** [comment]
@bduffany I totally agree with that. So the minimal execution could be without cb_compile_tester's projects and without any library examples testing.
